name: code_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_64:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - run: make test

    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  test_32:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - run: make test32

  test_highlevel:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v2
      with:
        go-version: "1.22"

    - name: GitHub Tag Name example
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"

    - run: make test-highlevel-nodocker
